Remove color from horizontal lines
SaswatPadhi/pseudocode.js pull request #48
Opened 2024-05-06 15:04 UTC by Mavoort

I hereby request that the colour of the horizontal lines be removed,
so that the pseudocode diagram looks the same on a website with a dark background.

This fixes Issue #47 .

2024-05-18 19:36 UTC, SaswatPadhi requested changes
Hi @Mavoort,

Thanks for this fix! LGTM, but I suggest simplifying the style.

2024-05-18 19:36 UTC, SaswatPadhi commented on static/pseudocode.css
> +    border-bottom-style: solid;
```suggestion
    border-top: 3px solid;
    border-bottom: 2px solid;
```

2024-05-18 19:36 UTC, SaswatPadhi commented on static/pseudocode.css
> +    border-bottom-style: solid;
```suggestion
    border-bottom: 2px solid;
```

2024-05-20 16:28 UTC, Mavoort commented
Thanks for the suggestion! I'm not an expert at CSS, so I didn't know that. It should be good now.

2024-05-20 17:10 UTC, SaswatPadhi approved these changes

2024-05-20 17:11 UTC, merged